### ISSUE TITLE
"Read Document" Button Text not Fully Displaying

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#625] opened 2015-09-16 18:24 UTC
See attached screen shot

<img width="478" alt="screen shot 2015-09-16 at 2 14 35 pm" src="https://cloud.githubusercontent.com/assets/2349231/9914186/97945076-5c7e-11e5-8fa0-17eed5d8638d.png">

**Comment by krues8dr** [comment] 2015-09-16 18:38
Dupe of #613

**Closed by krues8dr** 2015-09-16 18:38 UTC
Labels: Bug, UX / Usability
