### ISSUE TITLE
Sponsor's name does not appear on homepage

### ISSUE THREAD

**Issue by nickom** [opengovfoundation/madison#854] opened 2016-01-28 21:47 UTC
How it looks at https://drafts.dc.gov/ : 
<img width="709" alt="screen shot 2016-01-28 at 4 45 20 pm" src="https://cloud.githubusercontent.com/assets/3171982/12659775/992ce500-c5de-11e5-9cf2-3a5386fab837.png">

vs. the bill page itself https://drafts.dc.gov/docs/strengthening-transparency-and-open-access-to-government-amendment-act-of-2016 : 
<img width="860" alt="screen shot 2016-01-28 at 4 46 22 pm" src="https://cloud.githubusercontent.com/assets/3171982/12659807/b058c0c8-c5de-11e5-84a1-77c0d5dd19f7.png">

**Comment by krues8dr** [comment] 2016-01-28 22:08
Dupe of #712 - fix in branch that's waiting to be deployed.

**Closed by krues8dr** 2016-01-28 22:08 UTC
Labels: Bug

**Comment by nickom** [comment] 2016-01-28 22:23
Ah didn't see the other issue, sorry about that and yay to such a quick fix!
![sagan-awesome](https://cloud.githubusercontent.com/assets/3171982/12660809/be3665f6-c5e3-11e5-872a-9ad52229be3a.gif)
