### ISSUE TITLE
Nothing happens when I click "Submit" when creating a new group

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#508] opened 2015-03-16 18:15 UTC
I need to know my information has been submitted.

**Comment by cmbirk** [comment] 2015-03-16 18:36
This is most likely an issue with the `angular-growl` plugin.

**Comment by cmbirk** [comment] 2015-03-16 20:56
@leilis I'm not able to reproduce this.  What steps did you take, and what did it show you?

**Comment by leilis** [comment] 2015-03-16 21:01
@cmbirk that's strange, it's now working like it should. Earlier today if I signed in, clicked on "Want to create a group?" on the Group Management page, filled in some information, and clicked "Submit", nothing happened -- it didn't take me back to the groups page or show me the "Your group has been created!" message.

**Comment by cmbirk** [comment] 2015-03-16 21:11
Interesting.  I'll keep an eye out for it, but closing this issue.

**Closed by cmbirk** 2015-03-16 21:11 UTC
Labels: Difficulty (1): Easy enough!, UX / Usability
