### ISSUE TITLE
Hide Like/Flag buttons until Likes are fixed.

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#836] opened 2016-01-23 19:11 UTC
I can't `like` anything on drafts.dc.gov:

![image](https://cloud.githubusercontent.com/assets/4592/12532175/288ca6f2-c1db-11e5-8725-8286db9243a5.png)

![image](https://cloud.githubusercontent.com/assets/4592/12532180/3b1969cc-c1db-11e5-9b42-091ed3e5f53f.png)

It's happened on multiple separate comments on different threads.

**Comment by krues8dr** [comment] 2016-01-23 19:14
Yup, dupe of #683 :(

**Comment by konklone** [comment] 2016-01-23 19:22
Ah, sorry -- I did search for open issues with "likes" before opening. #683 is closed, so it didn't come up. Should #683 be re-opened til the fix is deployed?

**Comment by krues8dr** [comment] 2016-01-23 19:28
Sorry, also dupe of #778 though not obviously. :( :(

**Comment by konklone** [comment] 2016-01-23 19:30
Since #771 looks like a pretty big refactor, it might be good to make a quick interim patch that hides the like and flag buttons until it's deployed, since right now they are just broken.

**Comment by krues8dr** [comment] 2016-01-23 19:31
Fair point.

**Comment by sethetter** [comment] 2017-06-28 16:56
Likes/flags working in v4

**Closed by sethetter** 2017-06-28 16:56 UTC
Labels: Priority, Type: UX / Usability
