### ISSUE TITLE
Comment box should be multi-line

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#837] opened 2016-01-23 19:13 UTC
Entering and editing/revising long comments into the annotation box is difficult with a single-line box:

![image](https://cloud.githubusercontent.com/assets/4592/12532183/512c0120-c1db-11e5-8c26-add8cd9267e8.png)

**Comment by krues8dr** [comment] 2016-01-23 19:15
:+1:  Dupe of DCgov/dc-madison#61

**Closed** 2016-01-23 19:16 UTC
