### ISSUE TITLE
Comment box out of place

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#591] opened 2015-06-22 18:49 UTC
http://dev.mymadison.io/docs/san-francisco-open-data-legislation-2014
![screen shot 2015-06-22 at 2 48 28 pm](https://cloud.githubusercontent.com/assets/12156643/8289977/decb91f4-18ed-11e5-867b-9009a27262f3.png)

**Comment by cmbirk** [comment] 2015-06-23 20:15
Duplicate of #573.  Closing.

**Closed by cmbirk** 2015-06-23 20:15 UTC
Labels: Bug
