### ISSUE TITLE
Notification settings page is blank on drafts.dc.gov

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#840] opened 2016-01-23 19:16 UTC
The notification settings page is completely blank for me on drafts.dc.gov, as a logged in user:

![image](https://cloud.githubusercontent.com/assets/4592/12532204/d3ee1562-c1db-11e5-97f8-92c54f4dbf19.png)

**Comment by krues8dr** [comment] 2016-01-23 19:18
Dupe of #821

**Closed by krues8dr** 2016-01-23 19:18 UTC

**Comment by konklone** [comment] 2016-01-23 19:23
Thanks, should've searched first!
