### ISSUE TITLE
Document pages open at ~half page width (iphone, safari)

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#849] opened 2016-01-27 00:35 UTC
Other pages seem to largely fine (other than a few header lines that need more padding).

![img_0357](https://cloud.githubusercontent.com/assets/4269640/12599887/7475a0b6-c463-11e5-98fb-7a2f09770563.PNG)

**Comment by krues8dr** [comment] 2016-01-27 00:36
Hey @emanuelfeld which iPhone do you have, and what version of iOS are you running?  Thanks!

**Comment by emanuelfeld** [comment] 2016-01-27 00:37
iPhone 6 and looks like iOS 9.2

**Comment by krues8dr** [comment] 2016-01-27 00:37
Great, thanks!  We'll have a look!

**Comment by dkd903** [comment] 2016-02-21 06:22
Just took a look at this on my laptop (using Safari and Chrome debug). Looks like it is got something to do with the Uservoice Widget. Will do some more investigation. Please check the attached screenshots.
![screen shot 2016-02-21 at 1 21 06 am](https://cloud.githubusercontent.com/assets/233879/13201317/93a5b7ac-d839-11e5-8744-4bf4be477070.png)
![screen shot 2016-02-21 at 1 20 40 am](https://cloud.githubusercontent.com/assets/233879/13201318/93a7805a-d839-11e5-846d-9ca7f92c5e79.png)

**Comment by dkd903** [comment] 2016-02-21 06:32
UPDATE: I was wrong. Looks like it is the display property on the dc-meta elements. Unsetting the value from table-cell seems to fix this. Please advice. 

![screen shot 2016-02-21 at 1 30 24 am](https://cloud.githubusercontent.com/assets/233879/13201340/f53d98ee-d83a-11e5-89f4-e857e36e1eab.png)

**Comment by dkd903** [comment] 2016-02-21 17:36
Looks like this has been fixed already. Does mymadison.io have a older build? as I cannot reproduce this on my local dev build that has the latest changes.

![screen shot 2016-02-21 at 12 36 00 pm](https://cloud.githubusercontent.com/assets/233879/13204191/bc068786-d897-11e5-9c05-6f56a41650b9.png)

**Comment by krues8dr** [comment] 2016-02-21 17:43
mymadison.io does indeed have an older build, this might have been fixed with the other mobile issues and we didn't realize it?    `drafts.dc.gov` is looking right on my emulated version, @emanuelfeld can you confirm that this is or isn't fixed, please?

**Comment by emanuelfeld** [comment] 2016-02-21 19:26
Opening it up on my iphone, I have the same issue as before.

**Comment by dkd903** [comment] 2016-02-23 03:23
@krues8dr could you probably update mymadison.io with the latest build and then @emanuelfeld could take a look once again?

**Comment by sethetter** [comment] 2017-06-28 16:53
Fixed in v4

**Closed by sethetter** 2017-06-28 16:53 UTC
Labels: Priority, Type: Bug, Type: Mobile, Type: UX / Usability
