### ISSUE TITLE
Floating/Out of Place Annotations

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#632] opened 2015-09-17 21:46 UTC
Logged in and got this floating annotation (top right of the following screen shot):

<img width="1413" alt="screen shot 2015-09-17 at 5 44 05 pm" src="https://cloud.githubusercontent.com/assets/2349231/9946836/f7721aba-5d63-11e5-9b13-785016daa635.png">

**Comment by krues8dr** [comment] 2015-09-17 22:20
This is a dupe of #573, which only Seamus seems to be able to trigger for some reason.  I can't reproduce in Firefox or Chrome.

**Closed by krues8dr** 2015-09-17 22:20 UTC
Labels: Bug
